name: Docker Image CI

on:
  push:
    branches: [ "main", "fix/basic-ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/vmarlier/dummy-tester:${{ github.sha }}

    - name: Push the Docker image
      run: docker push ghcr.io/vmarlier/dummy-tester:${{ github.sha }}
